package com.pixelsface.towntalk.features.chat.data.model

import com.google.firebase.firestore.PropertyName
import com.google.firebase.firestore.ServerTimestamp
import com.pixelsface.towntalk.features.chat.domain.model.Message
import java.util.Date

/**
 * Data Transfer Object for a Message, used for Firestore interaction.
 */
data class MessageDto(
    @get:PropertyName("id")
    @set:PropertyName("id")
    var id: String = "", // Firestore might generate this if not set, or we set it client-side

    @get:PropertyName("chat_id")
    @set:PropertyName("chat_id")
    var chatId: String = "",

    @get:PropertyName("sender_id")
    @set:PropertyName("sender_id")
    var senderId: String = "",

    @get:PropertyName("sender_name")
    @set:PropertyName("sender_name")
    var senderName: String = "",

    @get:PropertyName("text")
    @set:PropertyName("text")
    var text: String = "",

    @ServerTimestamp
    @get:PropertyName("timestamp")
    @set:PropertyName("timestamp")
    var timestamp: Date? = null // Use Firestore ServerTimestamp
    // Future fields like imageUrl, audioUrl, status can be added here
) {
    // Default constructor for Firestore deserialization
    constructor() : this("", "", "", "", "", null)
}

// Mapper functions
fun MessageDto.toDomain(): Message {
    return Message(
        id = this.id,
        chatId = this.chatId,
        senderId = this.senderId,
        senderName = this.senderName,
        text = this.text,
        timestamp = this.timestamp?.time ?: 0L
    )
}

fun Message.toDto(): MessageDto {
    return MessageDto(
        id = this.id, // If id is generated by Firestore, this might be empty initially
        chatId = this.chatId,
        senderId = this.senderId,
        senderName = this.senderName,
        text = this.text,
        timestamp = if (this.timestamp == 0L) null else Date(this.timestamp) // Let Firestore set if null, or use client-provided timestamp
    )
} 